# Generated by Django 4.0.6 on 2022-10-07 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=20)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(null=True, upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='default_images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('standName', models.CharField(max_length=40)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='stand_images')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.area')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('credit', models.CharField(max_length=4, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.area')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prodName', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inStock', models.SmallIntegerField()),
                ('image', models.ImageField(null=True, upload_to='product_images')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('stand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stand')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.SmallIntegerField()),
                ('totalProdPrice', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='stand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stand'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='stand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.stand'),
        ),
    ]
