# Generated by Django 4.0.6 on 2022-11-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userType',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
