# Generated by Django 4.0.6 on 2022-11-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
    ]
