# Generated by Django 4.0.6 on 2022-11-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_order_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='totalProdPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
