# Generated by Django 4.0.6 on 2022-11-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_profile_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inStock',
            field=models.BooleanField(default=True),
        ),
    ]
