# Generated by Django 4.0.6 on 2022-11-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_product_instock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inStock',
        ),
    ]
