# Generated by Django 4.0.6 on 2022-11-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_product_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='profile_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
    ]
