# Generated by Django 4.0.6 on 2022-11-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_stand_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='stand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.stand'),
        ),
    ]
